# Generated by Django 3.0.5 on 2020-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoChat', '0008_auto_20200519_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmessage',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
